import { createHash, randomUUID } from "node:crypto";
import { lstat, mkdir, open, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { setTimeout as delay } from "node:timers/promises";

const SLUG = /^[a-z0-9][a-z0-9-]{0,79}$/;
const LANES = ["momus", "independent"];
const HEADERS = ["## TL;DR (For humans)", "## Scope", "## Verification strategy", "## Execution strategy", "## Todos", "## Final verification wave", "## Commit strategy", "## Success criteria"];

function value(argv, flag) { const i = argv.indexOf(flag); const inline = argv.find((x) => x.startsWith(`${flag}=`)); return i >= 0 ? argv[i + 1] : inline?.slice(flag.length + 1); }
function required(argv, flag) { const v = value(argv, flag)?.trim(); if (!v) throw new Error(`${flag} requires a value`); return v; }
function has(argv, flag) { return argv.includes(flag); }
function digest(text) { return createHash("sha256").update(text).digest("hex"); }
function validateSlug(slug) { if (!SLUG.test(slug)) throw new Error("slug must use lowercase letters, digits, and hyphens"); return slug; }
function paths(cwd, slug) { const root = path.resolve(cwd, ".omo"); return { root, draft: path.join(root, "drafts", `${slug}.md`), plan: path.join(root, "plans", `${slug}.md`), state: path.join(root, "ulw-plan", `${slug}.json`) }; }
function contained(root, target) { const rel = path.relative(root, target); if (!rel || rel.startsWith("..") || path.isAbsolute(rel)) throw new Error("path escapes .omo"); return rel; }
async function checkedLstat(file) { return lstat(file).catch((error) => error.code === "ENOENT" ? null : Promise.reject(error)); }
async function safeParent(root, target) { const rel = contained(root, target); await mkdir(root, { recursive: true }); let cursor = root; for (const part of ["", ...path.dirname(rel).split(path.sep).filter(Boolean)]) { if (part) cursor = path.join(cursor, part); let st = await checkedLstat(cursor); if (!st) { await mkdir(cursor); st = await lstat(cursor); } if (st.isSymbolicLink() || !st.isDirectory()) throw new Error(`refused unsafe path: ${cursor}`); } }
async function safeExistingFile(root, target) { const rel = contained(root, target); let cursor = root; for (const part of ["", ...rel.split(path.sep)]) { if (part) cursor = path.join(cursor, part); const st = await checkedLstat(cursor); if (!st) return null; if (st.isSymbolicLink()) throw new Error(`refused symlink path: ${cursor}`); const isTarget = cursor === target; if (isTarget ? !st.isFile() : !st.isDirectory()) throw new Error(`refused unsafe path: ${cursor}`); } return lstat(target); }
async function atomicJson(file, data) { const root = path.resolve(path.dirname(path.dirname(file))); await safeParent(root, file); const temp = `${file}.${process.pid}.${randomUUID()}.tmp`; try { await writeFile(temp, `${JSON.stringify(data, null, 2)}\n`, { flag: "wx" }); await rename(temp, file); } finally { await unlink(temp).catch((error) => { if (error.code !== "ENOENT") throw error; }); } }
async function readState(cwd, slug) { const p = paths(cwd, slug); if (!await safeExistingFile(p.root, p.state)) throw new Error("plan state does not exist"); return { p, state: JSON.parse(await readFile(p.state, "utf8")) }; }
async function withMutationLock(cwd, slug, action) { const p = paths(cwd, slug); const lock = path.join(p.root, "ulw-plan", `${slug}.lock`); await safeParent(p.root, lock); let handle; for (let attempt = 0; attempt < 100; attempt += 1) { try { handle = await open(lock, "wx", 0o600); break; } catch (error) { if (error.code !== "EEXIST") throw error; const st = await checkedLstat(lock); if (st?.isSymbolicLink() || (st && !st.isFile())) throw new Error("unsafe plan mutation lock"); if (st && Date.now() - st.mtimeMs > 300_000) { await unlink(lock); continue; } await delay(20); } } if (!handle) throw new Error("plan mutation lock timeout"); try { await handle.writeFile(`${process.pid} ${new Date().toISOString()}\n`); return await action(); } finally { await handle.close(); await unlink(lock).catch((error) => { if (error.code !== "ENOENT") throw error; }); } }

function draftText(slug, intent, reviewRequired) { return `---\nslug: ${slug}\nstatus: drafting\nintent: ${intent}\nreview_required: ${reviewRequired}\n---\n\n# Draft: ${slug}\n\n## Components (topology ledger)\n\n## Open assumptions (announced defaults)\n\n## Findings (cited - path:lines)\n\n## Decisions (with rationale)\n\n## Scope IN\n\n## Scope OUT (Must NOT have)\n\n## Open questions\n\n## Approval gate\nstatus: awaiting-approval\n`;
}
function planText(slug) { return `# ${slug} - Work Plan\n\n${HEADERS.map((h) => `${h}\n<fill>`).join("\n\n")}\n`; }
function lane() { return { status: "pending", workspace_root: null, runtime_home: null, target: null, round_id: null, plan_sha256: null, launch_id: null, session: null, result: null }; }

async function scaffold(cwd, argv) {
  const slug = validateSlug(argv.find((x) => !x.startsWith("--")) ?? ""); const intent = has(argv, "--unclear") ? "unclear" : has(argv, "--clear") ? "clear" : "unspecified"; const reviewRequired = has(argv, "--review-required"); const p = paths(cwd, slug);
  const draftExists = Boolean(await safeExistingFile(p.root, p.draft)); const stateExists = Boolean(await safeExistingFile(p.root, p.state));
  if (draftExists || stateExists) { if (!(draftExists && stateExists)) throw new Error("partial scaffold state exists"); process.stdout.write(`exists: ${path.relative(cwd, p.draft)}\n`); return 0; }
  if (await safeExistingFile(p.root, p.plan)) throw new Error("plan already exists before approval");
  await safeParent(p.root, p.draft); await writeFile(p.draft, draftText(slug, intent, reviewRequired), { flag: "wx" });
  await atomicJson(p.state, { version: 1, slug, phase: "awaiting_approval", intent, review_required: reviewRequired, draft_path: path.relative(cwd, p.draft), plan_path: path.relative(cwd, p.plan), draft_sha256: digest(await readFile(p.draft)), approval: null, review_round_id: null, round_status: null, plan_sha256: null, review: { momus: lane(), independent: lane() }, finalized_at: null });
  process.stdout.write(`created: ${path.relative(cwd, p.draft)}\nawaiting approval\n`); return 0;
}
async function approve(cwd, argv) { const slug = validateSlug(required(argv, "--slug")); const { p, state } = await readState(cwd, slug); if (state.phase !== "awaiting_approval") throw new Error(`approval blocked in phase ${state.phase}`); if (!await safeExistingFile(p.root, p.draft)) throw new Error("draft does not exist"); const live = digest(await readFile(p.draft)); if (live !== state.draft_sha256) throw new Error("draft changed; refresh scaffold state before approval"); if (await safeExistingFile(p.root, p.plan)) throw new Error("plan already exists before approval"); await safeParent(p.root, p.plan); await writeFile(p.plan, planText(slug), { flag: "wx" }); state.approval = { approved_by: required(argv, "--approved-by"), draft_sha256: live, at: new Date().toISOString() }; state.phase = state.review_required ? "review_requested" : "approved"; await atomicJson(p.state, state); process.stdout.write(`created: ${path.relative(cwd, p.plan)}\n${state.phase}: ${slug}\n`); return 0; }
async function reviewInit(cwd, argv) { const slug = validateSlug(required(argv, "--slug")); const { p, state } = await readState(cwd, slug); if (state.phase !== "review_requested" && state.phase !== "review_blocked") throw new Error(`review initialization blocked in phase ${state.phase}`); if (!state.approval || !state.review_required) throw new Error("review requires an approved review-required draft"); if (!await safeExistingFile(p.root, p.plan)) throw new Error("plan does not exist"); const planBody = await readFile(p.plan, "utf8"); if (HEADERS.some((h) => !planBody.includes(h)) || planBody.includes("<fill>")) throw new Error("complete the plan before review"); const planSha = digest(planBody); const round = randomUUID(); state.phase = "review_active"; state.round_status = "active"; state.review_round_id = round; state.plan_sha256 = planSha; for (const name of LANES) state.review[name] = { ...lane(), workspace_root: path.resolve(cwd), target: state.plan_path, round_id: round, plan_sha256: planSha, launch_id: randomUUID(), session: required(argv, `--${name}-session`), status: "in_flight" }; await atomicJson(p.state, state); process.stdout.write(`${JSON.stringify({ round_id: round, plan_sha256: planSha, review: state.review }, null, 2)}\n`); return 0; }
async function reviewReceipt(cwd, argv) { const slug = validateSlug(required(argv, "--slug")); const name = required(argv, "--lane"); if (!LANES.includes(name)) throw new Error("--lane must be momus or independent"); const { p, state } = await readState(cwd, slug); if (state.phase !== "review_active") throw new Error(`review receipt blocked in phase ${state.phase}`); const current = state.review[name]; const expected = { round_id: required(argv, "--round-id"), launch_id: required(argv, "--launch-id"), session: required(argv, "--session"), plan_sha256: required(argv, "--plan-sha256") }; for (const [key, val] of Object.entries(expected)) if (current[key] !== val) throw new Error(`stale or mismatched review receipt: ${key}`); if (current.status !== "in_flight" || state.round_status !== "active") throw new Error("duplicate or inactive review receipt"); if (!await safeExistingFile(p.root, p.plan) || digest(await readFile(p.plan)) !== state.plan_sha256) throw new Error("plan changed during review"); const result = required(argv, "--result"); if (!new Set(["approved", "changes_requested", "inconclusive"]).has(result)) throw new Error("invalid --result"); current.status = result; current.result = required(argv, "--evidence"); if (LANES.every((laneName) => state.review[laneName].status === "approved")) { state.round_status = "approved"; state.phase = "approved"; } else if (result !== "approved") { state.round_status = result; state.phase = "review_blocked"; } await atomicJson(p.state, state); process.stdout.write(`${name}: ${result}\n`); return 0; }
async function finalize(cwd, argv) { const slug = validateSlug(required(argv, "--slug")); const { p, state } = await readState(cwd, slug); if (state.phase !== "approved") throw new Error(`finalization blocked in phase ${state.phase}`); if (state.review_required && !LANES.every((n) => state.review[n].status === "approved")) throw new Error("both reviewer receipts must approve"); if (!await safeExistingFile(p.root, p.plan)) throw new Error("plan does not exist"); const plan = await readFile(p.plan, "utf8"); if (HEADERS.some((h) => !plan.includes(h)) || plan.includes("<fill>")) throw new Error("plan is incomplete"); const liveSha = digest(plan); if (state.review_required && liveSha !== state.plan_sha256) throw new Error("plan changed after reviewer receipts"); state.plan_sha256 = liveSha; state.phase = "final"; state.finalized_at = new Date().toISOString(); await atomicJson(p.state, state); process.stdout.write(`ULW_PLAN_DONE ${state.plan_path} sha256:${state.plan_sha256}\n`); return 0; }

export async function runUlwPlan(argv, cwd = process.cwd()) { try { const cmd = argv[0] ?? "help"; const args = argv.slice(1); if (cmd === "scaffold") { const slug = validateSlug(args.find((x) => !x.startsWith("--")) ?? ""); return await withMutationLock(cwd, slug, () => scaffold(cwd, args)); } if (new Set(["approve", "review-init", "review-receipt", "finalize"]).has(cmd)) { const slug = validateSlug(required(args, "--slug")); const actions = { approve, "review-init": reviewInit, "review-receipt": reviewReceipt, finalize }; return await withMutationLock(cwd, slug, () => actions[cmd](cwd, args)); } if (cmd === "status") { const { state } = await readState(cwd, validateSlug(required(args, "--slug"))); process.stdout.write(`${JSON.stringify(state, null, 2)}\n`); return 0; } process.stdout.write("Usage: ddalggak ulw-plan scaffold|approve|review-init|review-receipt|finalize|status ...\n"); return cmd === "help" ? 0 : 1; } catch (error) { process.stderr.write(`[ulw-plan] ${error.message}\n`); return 1; } }
