// Clean-room ULW research state machine. Written from observable
// requirements only; it contains no SUL-licensed upstream prose.
import { createHash } from "node:crypto";
import { lstat, mkdir, open, readFile, rename, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import { setTimeout as delay } from "node:timers/promises";

const ID = /^[A-Za-z0-9][A-Za-z0-9._-]{0,79}$/;
const FORMATS = new Set(["pdf", "docx", "markdown", "html", "slides", "json", "latex"]);
const CREDENTIAL_QUERY_KEY = /^(?:access_?token|api_?key|auth|authorization|bearer|client_?secret|credential|jwt|key|password|passwd|pwd|secret|signature|sig|token)$/i;
function val(argv, flag) { const i = argv.indexOf(flag); const x = argv.find((a) => a.startsWith(`${flag}=`)); return i >= 0 ? argv[i + 1] : x?.slice(flag.length + 1); }
function req(argv, flag) { const x = val(argv, flag)?.trim(); if (!x) throw new Error(`${flag} requires a value`); return x; }
function parseJson(argv, flag) { try { return JSON.parse(req(argv, flag)); } catch (error) { throw new Error(`${flag} must be valid JSON: ${error.message}`); } }
function id(x, label) { if (!ID.test(x)) throw new Error(`invalid ${label}`); return x; }
function sha(data) { return createHash("sha256").update(data).digest("hex"); }
function uniqueStrings(items, label) { if (!Array.isArray(items) || items.some((x) => typeof x !== "string" || !x.trim())) throw new Error(`${label} must be a JSON string array`); return [...new Set(items.map((x) => x.trim()))]; }
function loc(cwd, session) { const root = path.resolve(cwd, ".omo", "ulw-research"); return { root, dir: path.join(root, session), state: path.join(root, session, "state.json"), journal: path.join(root, session, "waves.jsonl") }; }
async function checkedLstat(file) { return lstat(file).catch((error) => error.code === "ENOENT" ? null : Promise.reject(error)); }
function contained(root, target, label) { const rel = path.relative(root, target); if (!rel || rel.startsWith("..") || path.isAbsolute(rel)) throw new Error(`${label} escapes allowed root`); return rel; }
async function safeDir(root, dir) { const rel = contained(root, dir, "state path"); await mkdir(root, { recursive: true }); let cursor = root; for (const part of ["", ...rel.split(path.sep).filter(Boolean)]) { if (part) cursor = path.join(cursor, part); let st = await checkedLstat(cursor); if (!st) { await mkdir(cursor); st = await lstat(cursor); } if (st.isSymbolicLink() || !st.isDirectory()) throw new Error("symlinked or non-directory research state is refused"); } }
async function safeFile(root, target, label) { const rel = contained(root, target, label); let cursor = root; for (const part of ["", ...rel.split(path.sep)]) { if (part) cursor = path.join(cursor, part); const st = await checkedLstat(cursor); if (!st) throw new Error(`${label} does not exist`); if (st.isSymbolicLink()) throw new Error(`${label} uses a symlinked path`); const isTarget = cursor === target; if (isTarget ? !st.isFile() : !st.isDirectory()) throw new Error(`${label} is not a regular contained file`); } return lstat(target); }
async function save(p, state) { await safeDir(p.root, p.dir); const tmp = `${p.state}.${process.pid}.${Date.now()}.tmp`; try { await writeFile(tmp, `${JSON.stringify(state, null, 2)}\n`, { flag: "wx" }); await rename(tmp, p.state); } finally { await unlink(tmp).catch((error) => { if (error.code !== "ENOENT") throw error; }); } }
async function load(cwd, argv) { const session = id(req(argv, "--session-id"), "session id"); const p = loc(cwd, session); await safeFile(p.root, p.state, "research state"); return { p, state: JSON.parse(await readFile(p.state, "utf8")) }; }
async function append(p, item) { await safeFile(p.root, p.journal, "research journal"); await writeFile(p.journal, `${JSON.stringify(item)}\n`, { flag: "a" }); }
async function fileReceipt(cwd, input, expected) { const root = path.resolve(cwd); const full = path.resolve(root, input); const rel = contained(root, full, "artifact"); const st = await safeFile(root, full, "artifact"); if (st.size === 0) throw new Error("artifact must be non-empty"); const actual = sha(await readFile(full)); if (expected && expected !== actual) throw new Error("stale artifact digest"); return { path: rel.split(path.sep).join("/"), sha256: actual, bytes: st.size }; }
async function withMutationLock(cwd, session, action) { const p = loc(cwd, session); await safeDir(p.root, p.dir); const lock = path.join(p.dir, "mutation.lock"); let handle; for (let attempt = 0; attempt < 100; attempt += 1) { try { handle = await open(lock, "wx", 0o600); break; } catch (error) { if (error.code !== "EEXIST") throw error; const st = await checkedLstat(lock); if (st?.isSymbolicLink() || (st && !st.isFile())) throw new Error("unsafe research mutation lock"); if (st && Date.now() - st.mtimeMs > 300_000) { await unlink(lock); continue; } await delay(20); } } if (!handle) throw new Error("research mutation lock timeout"); try { await handle.writeFile(`${process.pid} ${new Date().toISOString()}\n`); return await action(); } finally { await handle.close(); await unlink(lock).catch((error) => { if (error.code !== "ENOENT") throw error; }); } }

async function init(cwd, argv) {
  const session = id(req(argv, "--session-id"), "session id"); const p = loc(cwd, session);
  if (await readFile(p.state).catch(() => null)) throw new Error("research session already exists");
  const axes = uniqueStrings(parseJson(argv, "--axes-json"), "--axes-json"); if (axes.length < 3) throw new Error("research requires at least three orthogonal axes");
  const proposal = req(argv, "--format-proposal");
  const state = { version: 2, session_id: session, topic: req(argv, "--topic"), started_at: new Date().toISOString(), phase: "awaiting_format", format_proposal: proposal, accepted_design: null, axes, wave: 0, expansion_waves: 0, waves: [], open_leads: [], seen_leads: [], closed_leads: [], claims: {}, gates: { format_accepted: false, convergence: false, claims_evidence: false, artifact: false, qa: false }, final: null };
  await save(p, state); await writeFile(p.journal, "", { flag: "wx" }); process.stdout.write(`created: ${path.relative(cwd, p.state)}\nawaiting format acceptance\n`); return 0;
}
async function acceptFormat(cwd, argv) { const { p, state } = await load(cwd, argv); if (state.phase !== "awaiting_format") throw new Error("format acceptance is no longer pending"); const format = req(argv, "--format").toLowerCase(); if (!FORMATS.has(format)) throw new Error("unsupported format"); state.accepted_design = { format, template: req(argv, "--template"), accepted_by: req(argv, "--accepted-by"), at: new Date().toISOString() }; state.gates.format_accepted = true; state.phase = "research"; await save(p, state); process.stdout.write(`format accepted: ${format}\n`); return 0; }
async function wave(cwd, argv) {
  const { p, state } = await load(cwd, argv); if (!state.gates.format_accepted || state.phase !== "research" || state.gates.convergence) throw new Error("format proposal must be accepted and research active before worker dispatch");
  const mode = req(argv, "--mode").toUpperCase(); if (!new Set(["EXPAND", "CONVERGE"]).has(mode)) throw new Error("--mode must be EXPAND or CONVERGE");
  const returns = parseJson(argv, "--returns-json"); if (!Array.isArray(returns)) throw new Error("--returns-json must be an array");
  const closed = uniqueStrings(parseJson(argv, "--closed-leads-json"), "--closed-leads-json");
  if (mode === "EXPAND") {
    if (returns.length === 0) throw new Error("EXPAND wave requires worker returns");
    for (const item of returns) {
      if (!item || typeof item !== "object" || typeof item.axis !== "string" || !item.axis.trim() || typeof item.findings !== "string" || !item.findings.trim() || !Array.isArray(item.sources) || item.sources.some((source) => typeof source !== "string" || !source.trim()) || !Array.isArray(item.expand)) throw new Error("every worker return needs axis, findings, string sources, and EXPAND tail");
    }
    if (state.wave === 0) { const covered = new Set(returns.map((x) => x.axis)); for (const axis of state.axes) if (!covered.has(axis)) throw new Error(`first wave missing axis: ${axis}`); }
  }
  const newlySeen = [];
  for (const item of returns) for (const lead of item.expand ?? []) { if (typeof lead !== "string" || !lead.trim()) throw new Error("EXPAND leads must be non-empty strings"); const clean = lead.trim(); if (!state.seen_leads.includes(clean)) { state.seen_leads.push(clean); state.open_leads.push(clean); newlySeen.push(clean); } }
  for (const lead of closed) { if (!state.seen_leads.includes(lead)) throw new Error(`cannot close unseen lead: ${lead}`); state.open_leads = state.open_leads.filter((x) => x !== lead); if (!state.closed_leads.includes(lead)) state.closed_leads.push(lead); }
  if (mode === "CONVERGE") { if (state.expansion_waves < 2) throw new Error("convergence requires at least two EXPAND waves"); if (state.open_leads.length) throw new Error("convergence blocked by open leads"); }
  const event = { wave: state.wave + 1, mode, returns, newly_seen_leads: newlySeen, closed_leads: closed, open_leads_after: [...state.open_leads], at: new Date().toISOString() };
  await append(p, event); state.wave += 1; if (mode === "EXPAND") state.expansion_waves += 1; state.waves.push(event); if (mode === "CONVERGE") { state.gates.convergence = true; state.phase = "converged"; } await save(p, state); process.stdout.write(`wave ${state.wave}: ${mode}\n`); return 0;
}
function mutableResearch(state) { if (!new Set(["research", "converged"]).has(state.phase) || state.final) throw new Error(`research mutation blocked in phase ${state.phase}`); }
async function claim(cwd, argv) { const { p, state } = await load(cwd, argv); mutableResearch(state); const claimId = id(req(argv, "--claim-id"), "claim id"); if (state.claims[claimId]) throw new Error("claim already exists"); const risk = req(argv, "--risk"); if (!new Set(["low", "high"]).has(risk)) throw new Error("--risk must be low or high"); const type = req(argv, "--claim-type"); state.claims[claimId] = { text: req(argv, "--text"), intent_id: req(argv, "--intent-id"), risk, claim_type: type, status: "unsupported", evidence: [] }; state.gates.claims_evidence = false; await save(p, state); process.stdout.write(`claim added: ${claimId}\n`); return 0; }
async function evidence(cwd, argv) { const { p, state } = await load(cwd, argv); mutableResearch(state); const claimId = id(req(argv, "--claim-id"), "claim id"); const target = state.claims[claimId]; if (!target) throw new Error("unknown claim"); const sourceType = req(argv, "--source-type"); if (sourceType === "self-report" || sourceType === "model-summary") throw new Error("self-reported evidence is not admissible"); const domain = req(argv, "--domain"); let receipt; if (val(argv, "--artifact")) receipt = await fileReceipt(cwd, req(argv, "--artifact"), req(argv, "--sha256")); else { const url = new URL(req(argv, "--url")); if (!new Set(["http:", "https:"]).has(url.protocol)) throw new Error("evidence URL must be http(s)"); if (url.username || url.password) throw new Error("evidence URL must not contain userinfo credentials"); for (const key of url.searchParams.keys()) if (CREDENTIAL_QUERY_KEY.test(key.replaceAll(/[-.]/g, "_"))) throw new Error(`evidence URL must not contain credential query parameter: ${key}`); if (domain.toLowerCase() !== url.hostname.toLowerCase()) throw new Error("evidence domain must match URL hostname"); receipt = { url: url.href }; } const validAt = req(argv, "--valid-at"); if (!Number.isFinite(Date.parse(validAt))) throw new Error("--valid-at must be a valid date or timestamp"); target.evidence.push({ source_type: sourceType, domain, observer_group: req(argv, "--observer-group"), valid_at: validAt, primary: argv.includes("--primary"), counter_search: argv.includes("--counter-search"), locator: req(argv, "--locator"), ...receipt, recorded_at: new Date().toISOString() }); target.status = "candidate"; await save(p, state); process.stdout.write(`evidence recorded: ${claimId}\n`); return 0; }
function claimPasses(claim) { if (!claim.evidence.length) return false; if (claim.risk !== "high" || claim.claim_type === "code") return true; const domains = new Set(claim.evidence.map((x) => x.domain)); const groups = new Set(claim.evidence.map((x) => x.observer_group)); return domains.size >= 2 && groups.size >= 2 && claim.evidence.some((x) => x.primary) && claim.evidence.some((x) => x.counter_search) && claim.evidence.every((x) => x.valid_at); }
async function finalize(cwd, argv) {
  const { p, state } = await load(cwd, argv); if (state.phase !== "converged" || state.final || !state.gates.convergence) throw new Error("convergence gate failed or research already finalized");
  const failed = Object.entries(state.claims).filter(([, claim]) => !claimPasses(claim)).map(([claimId]) => claimId); if (!Object.keys(state.claims).length || failed.length) throw new Error(`claims/evidence gate failed: ${failed.join(",") || "no claims"}`); for (const claim of Object.values(state.claims)) claim.status = "supported"; state.gates.claims_evidence = true;
  const format = req(argv, "--format").toLowerCase(); if (format !== state.accepted_design.format) throw new Error("final format differs from accepted design");
  const artifact = await fileReceipt(cwd, req(argv, "--artifact"), req(argv, "--artifact-sha256")); const assets = parseJson(argv, "--assets-json"); if (!Array.isArray(assets)) throw new Error("--assets-json must be an array"); const assetReceipts = []; for (const item of assets) assetReceipts.push(await fileReceipt(cwd, item.path, item.sha256)); state.gates.artifact = true;
  const qaReceipt = await fileReceipt(cwd, req(argv, "--qa-receipt"), req(argv, "--qa-sha256")); const qa = JSON.parse(await readFile(path.resolve(cwd, qaReceipt.path), "utf8")); if (qa.verdict !== "pass" || qa.artifact_sha256 !== artifact.sha256 || !qa.reviewer || qa.reviewer === "self" || qa.rendered_pages_pass !== true || qa.proofread_pass !== true) throw new Error("QA receipt gate failed"); state.gates.qa = true;
  const domains = new Set(Object.values(state.claims).flatMap((claim) => claim.evidence.map((e) => e.domain))); const sources = new Set(Object.values(state.claims).flatMap((claim) => claim.evidence.map((e) => e.url ?? e.path)));
  state.final = { format, artifact, assets: assetReceipts, qa_receipt: qaReceipt, counts: { sources: sources.size, domains: domains.size, waves: state.waves.length, leads: state.seen_leads.length }, at: new Date().toISOString() }; state.phase = "final"; await save(p, state); process.stdout.write(`ULW_RESEARCH_DONE ${artifact.path} sha256:${artifact.sha256}\n`); return 0;
}

export async function runUlwResearch(argv, cwd = process.cwd()) { try { const cmd = argv[0] ?? "help"; const args = argv.slice(1); if (new Set(["init", "accept-format", "wave", "claim", "record-evidence", "finalize"]).has(cmd)) { const session = id(req(args, "--session-id"), "session id"); const actions = { init, "accept-format": acceptFormat, wave, claim, "record-evidence": evidence, finalize }; return await withMutationLock(cwd, session, () => actions[cmd](cwd, args)); } if (cmd === "status") { const { state } = await load(cwd, args); process.stdout.write(`${JSON.stringify(state, null, 2)}\n`); return 0; } process.stdout.write("Usage: ddalggak ulw-research init|accept-format|wave|claim|record-evidence|finalize|status ...\n"); return cmd === "help" ? 0 : 1; } catch (error) { process.stderr.write(`[ulw-research] ${error.message}\n`); return 1; } }
