// Always-loaded skill hot-path anchors and banned runtime terms.

export const forbiddenHotPathTemplateSentinels = [
  {
    pattern: /## 부모 이슈\r?\n#<parent-number>/,
    description: "full issue body template",
  },
  {
    pattern: /Plan → Issue Body 필드 매핑 체크리스트/,
    description: "plan-to-issue checklist detail",
  },
  {
    pattern: /Goal, Authorized files, Forbidden files\/actions/,
    description: "worker BRIEF contract body",
  },
  {
    pattern: /## 생성된 Issue 목록/,
    description: "generated issue list template",
  },
  {
    pattern: /LANE_READY: Phase Y W<번호>/,
    description: "legacy lane-ready worker output template",
  },
  {
    pattern: /## Full Procedure\r?\n(?:.|\n){0,200}git fetch --prune/,
    description: "low-frequency full procedure command block",
  },
  {
    pattern: /## Reviewer Prompt\r?\n(?:.|\n){0,200}Critical\/High/,
    description: "low-frequency review prompt body",
  },
  {
    pattern: /### Quality Lens Router Output\r?\n- Applicable gate families:/,
    description: "inline show-doc quality lens detail block",
  },
  {
    pattern: /### Evidence Contract\r?\n- Required evidence:/,
    description: "inline show-doc evidence contract detail block",
  },
  {
    pattern: /### Frontend Design Brief\r?\n- Product\/user context/,
    description: "inline show-doc frontend design detail block",
  },
  {
    pattern: /### Vercel Agent Skills Gate\r?\n- Applicable upstream skill families/,
    description: "inline show-doc Vercel gate detail block",
  },
];

export const bannedTerms = [
  "TeamCreate",
  "SendMessage",
  "TaskList",
  "TaskGet",
  "TaskOutput",
  "ScheduleWakeup",
  "AskUserQuestion",
  ".claude",
  "CLAUDE.md",
  "teammate",
];
// Keep always-loaded router/core invariants in the hot-path SKILL.md arrays.
// Detailed gate/rubric anchors belong in the reference arrays below so SKILL.md can stay compact without losing guardrails.

export const requiredSkillHotPathAnchors = [
  "URL beats cwd",
  "owner/repo/number",
  "cwd remote does not match",
  "Issue comments matter",
  "Manual merge only",
  "Approval-comment policy",
  "Issue-PRs by default",
  "Runtime contract language",
  "references/agent-runtime-contract.md",
  "Task Scope Contract",
  "Context Assembly Manifest",
  "Resume Snapshot",
  "Control-flow ownership",
  "tool capability boundary",
  "task scope contract",
  "out-of-scope diff",
  "scope-expansion failure",
  "Quality Lens Router",
  "Required references",
  "Domain gate is a lens, not a mandate",
  "Wiki Context First",
  "references/wiki-context-preflight.md",
  "Wiki Bridge",
  "references/wiki-bridge.md",
  "getwiki",
  "read-only retrieval",
  "setwiki",
  "approval-gated write",
  "Evidence Contract",
  "references/evidence-contract.md",
  "Blocking evidence gaps",
  "No evidence, no readiness or approval",
  "Simplicity / Deletability Gate",
  "references/simplicity-deletability-gate.md",
  "small direct change first",
  "why any proposed abstraction is necessary",
  "Core Invariants Reference",
  "references/core-invariants.md",
  "Self-created complexity is a defect",
  "no silent fallback",
  "raw UTF-8",
];

export const requiredClaudeSkillHotPathAnchors = [
  "URL beats cwd",
  "GitHub URL 처리 기준",
  "owner/repo/number",
  "cwd remote가 URL repo와 다르면",
  "Issue comments matter",
  "Manual merge only",
  "approval-comment policy",
  "Issue-PRs by default",
  "Runtime contract language",
  "references/agent-runtime-contract.md",
  "Task Scope Contract",
  "Context Assembly Manifest",
  "Resume Snapshot",
  "Control-flow ownership",
  "Quality Lens Router Output",
  "Required references",
  "Domain gate is a lens, not a mandate",
  "Wiki Context First",
  "references/wiki-context-preflight.md",
  "Wiki Bridge",
  "references/wiki-bridge.md",
  "getwiki",
  "read-only retrieval",
  "setwiki",
  "approval-gated write",
  "Evidence Contract",
  "references/evidence-contract.md",
  "Blocking evidence gaps",
  "Simplicity / Deletability Gate",
  "references/simplicity-deletability-gate.md",
  "small direct change first",
  "why is this abstraction necessary?",
  "Core Invariants Reference",
  "references/core-invariants.md",
  "raw UTF-8",
];
