// Reference-document anchor contracts grouped away from the aggregate adapter.

export const requiredEvidenceReferenceAnchors = [
  "Evidence Contract",
  "UI/design/frontend",
  "Deploy/release/env",
  "Performance",
  "Bugfix/regression",
  "Security/auth/privacy",
  "Data/API/backend",
  "not-applicable: <reason>",
  "High",
  "APPROVE",
];

export const requiredSimplicityReferenceAnchors = [
  "Simplicity / Deletability Gate",
  "small direct change first",
  "Why is this abstraction necessary?",
  "one-off abstraction",
  "default severity: High",
  "human readability",
  "SOLID",
  "do not outrank human readability",
  "client-side patch",
  "Non-Goals",
];

export const requiredRegressionLibraryReferenceAnchors = [
  "Continuous Regression Library",
  "durable reference material, not session memory",
  "Regression Library Candidate",
  "Medium/High pattern",
  "Symptom:",
  "Generalized failure class:",
  "Detection signal:",
  "Blocking review rule:",
  "Minimal fixture/evidence idea:",
  "Related gates:",
  "Generic AI UI",
  "Unnecessary provider/helper/wrapper",
  "Silent fallback",
  "Server/client boundary violation",
  "Token leakage",
  "Screenshot-free UI approval",
  "Production deploy without explicit request",
  "Overfitted incident rule",
  "Test-after instead of TDD",
  "Readability-hostile pattern application",
];

export const requiredRegressionLibraryClasses = [
  "Generic AI UI",
  "Unnecessary provider/helper/wrapper",
  "Silent fallback",
  "Server/client boundary violation",
  "Token leakage",
  "Screenshot-free UI approval",
  "Production deploy without explicit request",
  "Overfitted incident rule",
  "Test-after instead of TDD",
  "Readability-hostile pattern application",
];

export const requiredRegressionLibraryFields = [
  "Symptom:",
  "Generalized failure class:",
  "Detection signal:",
  "Blocking review rule:",
  "Minimal fixture/evidence idea:",
  "Related gates:",
];

export const requiredAgentRuntimeContractAnchors = [
  "Agent Runtime Contract",
  "Task Scope Contract",
  "Context Assembly Manifest",
  "Resume Snapshot",
  "Control-flow ownership",
  "tool capability boundary",
  "task scope contract",
  "conductor/reviewer-owned",
  "Non-goals",
];

export const requiredCoreInvariantReferenceAnchors = [
  "Core Invariants Reference",
  "URL beats cwd",
  "Issue comments matter",
  "No implicit dependencies",
  "Manual merge only",
  "Issue-PRs by default",
  "Runtime contract language",
  "Gate Verdict Vocabulary Index",
  "references/gate-verdict-vocabulary.md",
  "Task Scope Contract",
  "Context Assembly Manifest",
  "Resume Snapshot",
  "Control-flow ownership",
  "tool capability boundary",
  "task scope contract",
  "out-of-scope diff",
  "scope-expansion failure",
  "Diff Footprint / Scope Expansion Review",
  "Small focused workers, explicit orchestration",
  "Counterargument Pass",
  "weak assumptions",
  "evidence that would disprove readiness",
  "smaller or more direct change",
  "Blocking evidence gaps",
  "No evidence, no readiness or approval",
  "rendered evidence",
  "route evidence",
  "viewport evidence",
  "rendered DOM evidence",
  "screenshot evidence",
  "fallback evidence",
  "contract graph evidence",
  "Transitive rendered fallback audit",
  "list/detail surface",
  "shared card/media primitive",
  "Self-created complexity is a defect",
  "forced modularization",
  "Client-side patches",
  "mock-only tests",
  "one-off abstraction",
  "human readability/deletability",
  "SOLID",
  "Analytics privacy",
  "raw search terms",
  "prompt titles",
  "prompt bodies",
  "full query strings",
  "knowledge extraction",
  "harness-engineering/*",
  "principles/*",
  "frontend/*",
  "llm-wiki/*",
  "PR numbers",
  "commit SHAs",
  "single-session completion logs",
  "incident records",
  "durable reusable knowledge",
  "Component methodology gate",
  "main component only assembles",
  "ComponentName.parts.tsx",
  "ComponentName.utils.ts",
  "satisfies Record<...>",
  "public visual-contract classes",
  "no silent fallback",
  "raw UTF-8",
  "ensure_ascii=False",
];

export const requiredPromptSafetyReferenceAnchors = [
  "Prompt Safety / Brief Compiler",
  "Prompt Audit",
  "Goal clarity",
  "Source of truth",
  "Scope boundary",
  "Validation path",
  "Question need",
  "Risk level",
  "prompt grill-me",
  "Unsafe Prompt Gate",
  "READY_FOR_BRIEF",
  "NEEDS_CLARIFICATION",
  "BLOCKED_UNSAFE",
  "DISCOVERY_ONLY",
  "PROMPT_DONE",
];

export const requiredWikiBridgeReferenceAnchors = [
  "Wiki Bridge Contract",
  "admission and approval boundary",
  "getwiki bridge",
  "read-only retrieval",
  "Wiki Context Manifest",
  "setwiki bridge",
  "approval-gated write",
  "explicit user approval",
  "pjw-icloud-llm-wiki",
  "Forbidden surfaces",
  "Do not modify source skill files for the `getwiki` wrapper",
  "Do not modify source skill files for the `setwiki` wrapper",
  "Do not mutate the user's iCloud wiki tree",
  "Do not mutate wiki `raw/` sources",
  "Do not inline iCloud/QMD/setwiki implementation details into `SKILL.md`",
  "Do not change CLI routing (`bin/**`) merely to add wiki bridge behavior",
  "wiki-growth-triage.md",
  "The smallest durable surface wins",
];

export const requiredReadmeQualityAnchors = [
  "## Quality Defaults",
  "Runtime contract guardrails",
  "Task Scope Contract",
  "Context Assembly Manifest",
  "Resume Snapshot",
  "Control-flow ownership",
  "tool capability boundary",
  "task scope contract",
  "out-of-scope diff",
  "scope-expansion failure",
];
