// Subcommand execution, permission-profile, heading, and required-command contracts.

export const modePermissionProfiles = {
  "source-edit": { sourceEditAllowed: true, githubWriteAllowed: false },
  "review-fix": { sourceEditAllowed: true, githubWriteAllowed: true },
  "read-only": { sourceEditAllowed: false, githubWriteAllowed: false },
  "plan-only": { sourceEditAllowed: false, githubWriteAllowed: false },
  "github-write": { sourceEditAllowed: false, githubWriteAllowed: true },
  "local-destructive": { sourceEditAllowed: false, githubWriteAllowed: false },
  "repo-external-write": { sourceEditAllowed: false, githubWriteAllowed: false },
  "approval-gated-write": { sourceEditAllowed: false, githubWriteAllowed: false },
};

export const subcommandExecutionContracts = {
  start: {
    mode: "source-edit",
    sourceEditAllowed: true,
    githubWriteAllowed: false,
    requiredReferences: [
      "wiki-context-preflight.md",
      "2026-06-04-brain-v0-wiki-authority-in-ddalggak.md",
      "quality-lens-router.md",
      "evidence-contract.md",
      "simplicity-deletability-gate.md",
      "agent-runtime-contract.md",
      "core-invariants.md",
      "deep-interview-readiness-gate.md",
      "start-workflow.md",
    ],
    stopCondition: "Stop on stale base, missing issue body/comments, duplicate PR, or required files outside the issue-owned scope.",
    completionSignal: "ISSUE_PR_READY",
  },
  review: {
    mode: "review-fix",
    sourceEditAllowed: true,
    githubWriteAllowed: true,
    requiredReferences: [
      "wiki-context-preflight.md",
      "2026-06-04-brain-v0-wiki-authority-in-ddalggak.md",
      "quality-lens-router.md",
      "evidence-contract.md",
      "simplicity-deletability-gate.md",
      "core-invariants.md",
      "regression-library.md",
      "cross-review-loop.md",
      "human-review-feedback-loop.md",
      "ci-failure-triage-loop.md",
      "security-posture-gate.md",
    ],
    stopCondition: "Stop before APPROVE if current-head CI is not terminal green/skipped, blockers remain, or wiki/evidence preflight has blocking gaps.",
    completionSignal: "REVIEW_DONE",
  },
  status: {
    mode: "read-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["status.md", "pr-check-evidence-bundle.md"],
    stopCondition: "Stop after a live state snapshot and next-action recommendation.",
    completionSignal: "STATUS_DONE",
  },
  plan: {
    mode: "plan-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: [
      "wiki-context-preflight.md",
      "2026-06-04-brain-v0-wiki-authority-in-ddalggak.md",
      "wiki-bridge.md",
      "quality-lens-router.md",
      "evidence-contract.md",
      "simplicity-deletability-gate.md",
      "core-invariants.md",
      "deep-interview-readiness-gate.md",
      "ralplan-critic-consensus.md",
      "issue-ready-plan.md",
    ],
    stopCondition: "Stop after an issue-ready plan with evidence/unknowns and PR topology.",
    completionSignal: "PLAN_DONE",
  },
  issue: {
    mode: "github-write",
    sourceEditAllowed: false,
    githubWriteAllowed: true,
    requiredReferences: ["plan-to-issues.md"],
    stopCondition: "Stop after live issue URLs/labels/assignees/body UTF-8 verification or on metadata permission failure.",
    completionSignal: "ISSUE_DONE",
  },
  clean: {
    mode: "local-destructive",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["merge-cleanup.md"],
    stopCondition: "Stop on dirty, ambiguous, unmerged, or non-ancestor worktrees/branches.",
    completionSignal: "CLEAN_DONE",
  },
  ship: {
    mode: "github-write",
    sourceEditAllowed: false,
    githubWriteAllowed: true,
    requiredReferences: ["ship.md"],
    stopCondition: "Stop after PR creation/current-head publication evidence or on no-diff/scope/validation blocker.",
    completionSignal: "SHIP_DONE",
  },
  retro: {
    mode: "repo-external-write",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["retrospective.md", "retrospective-workflow.md", "wiki-growth-triage.md"],
    stopCondition: "Stop after reusable lessons are separated from transient incident records.",
    completionSignal: "RETRO_DONE",
  },
  prompt: {
    mode: "plan-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["prompt-optimizer.md", "prompt-skill-optimization-staging.md"],
    stopCondition: "Stop with READY_FOR_BRIEF, NEEDS_CLARIFICATION, BLOCKED_UNSAFE, or DISCOVERY_ONLY.",
    completionSignal: "PROMPT_DONE",
  },
  tune: {
    mode: "plan-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["tune-goal.md"],
    stopCondition: "Stop after a scoped brief or explicit blockers.",
    completionSignal: "TUNE_DONE",
  },
  forge: {
    mode: "plan-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["forge-goal.md"],
    stopCondition: "Stop after verifiable criteria or explicit gaps.",
    completionSignal: "FORGE_DONE",
  },
  spark: {
    mode: "plan-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["spark-goal.md"],
    stopCondition: "Stop after goal text and validation checklist.",
    completionSignal: "SPARK_DONE",
  },
  check: {
    mode: "read-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["local-diff-check.md"],
    stopCondition: "Stop after findings and exact validation gaps are reported.",
    completionSignal: "CHECK_DONE",
  },
  getwiki: {
    mode: "read-only",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["wiki-bridge.md", "2026-06-04-brain-v0-wiki-authority-in-ddalggak.md"],
    stopCondition: "Stop after cited wiki sources or retrieval gaps are reported.",
    completionSignal: "GETWIKI_DONE",
  },
  setwiki: {
    mode: "approval-gated-write",
    sourceEditAllowed: false,
    githubWriteAllowed: false,
    requiredReferences: ["wiki-bridge.md", "2026-06-04-brain-v0-wiki-authority-in-ddalggak.md", "wiki-growth-triage.md"],
    stopCondition: "Stop at review-only plan unless explicit approval is present; then stop after wiki write verification.",
    completionSignal: "SETWIKI_DONE",
  },
};

export const requiredSubcommands = [
  "start",
  "review",
  "status",
  "plan",
  "issue",
  "clean",
  "ship",
  "retro",
  "prompt",
  "tune",
  "forge",
  "spark",
  "check",
  "getwiki",
  "setwiki",
];

export const requiredClaudeHeadings = {
  start: "Start Workflow",
  review: "Cross-Review Loop",
  status: "Status",
  plan: "Issue-Ready Plan",
  issue: "Plan to Issues",
  clean: "Merge Cleanup",
  ship: "Ship",
  retro: "Retrospective",
  prompt: "Prompt Optimizer",
  tune: "Tune Goal Brief",
  forge: "Forge Acceptance Criteria",
  spark: "Spark Runtime Goal",
  check: "Local Diff Check",
  getwiki: "GetWiki Bridge",
  setwiki: "SetWiki Bridge",
};
